mailjet:
  key: '9e9dd5e4e26970c1735474a58e3b1b7d'
  secret: 'a37cc4ad8146df85267d63a91e09cc7f'
campaign:
  id: 19777
  title: "Week In Review, March 14th, 2021"
  subject: "DashKite Newsletter: Week In Review"
  sender:
    id: 11833
    name: "Dan Yoder"
    email: "dan@dashkite.com"
  list: 17656
  date: Now
  markdown: |
    # This Is A Test

    Let's see if we can get this working.
  test:
    name: Dan Yoder
    email: dan@dashkite.com
